### ISSUE TITLE
Copy to clipboard not working on iPad

### ISSUE THREAD

**Issue by SimonC-24** [vaadin4qbanos/vaadin-jsclipboard-addon#5]
Your example works great on PC browsers, but not on iPad. If I copy to clipboard on iPad, I get 'undefined'. Any solution for that?

Cheers, Simon

**Comment by rubenqba** [comment]
I'm willing to help, but I dont have an iPad to test the problem. If you
want you can check it yourself and make a PR.

**Comment by SimonC-24** [comment]
Thanks for a quick response.

You can test it in a Chrome browser - open 'Inspect mode', Toggle device manager and select iPad. From there open your example and 'Copy to clipboard'. When I follow these steps, I do get 'Undefined'.

Cheers, Simon

**Comment by rubenqba** [comment]
Ok, the problem with the demo is to capture the text of the TextArea, the JavaScript function should be performed in the context of the call, so in this case we use the BlurListener and to work must click on the TextArea first and then click "Copy to Clipboard" button.
In a realistic implementation should use a similar strategy. I solved the example so that the focus always start in the TextArea and force the execution of the listener. Now it works.
